import apiClient from './axios';
import { Agent } from '@/types';

export interface CreateAgentRequest {
  full_name: string;
  // Note: username, agent_code, and pin are auto-generated by backend
  status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'TERMINATED';
}

export interface UpdateAgentRequest {
  full_name?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'TERMINATED';
  depot_id?: string; // Allow depot reassignment
  // Note: username auto-generated if missing, agent_code and pin cannot be updated
}

class AgentService {
  /**
   * Get all agents (filtered by depot scope automatically on backend)
   */
  async getAll(): Promise<Agent[]> {
    const response = await apiClient.get<Agent[]>('/agents');
    return response.data;
  }

  /**
   * Get a single agent by ID
   */
  async getOne(id: string): Promise<Agent> {
    const response = await apiClient.get<Agent>(`/agents/${id}`);
    return response.data;
  }

  /**
   * Create a new agent
   * Requires DEPOT_ADMIN or SUPER_ADMIN role
   * @param data - Agent data
   * @param depotId - Required for SUPER_ADMIN to specify which depot the agent belongs to
   */
  async create(data: CreateAgentRequest, depotId?: string): Promise<Agent> {
    const config = depotId ? {
      headers: { 'x-depot-id': depotId }
    } : {};
    const response = await apiClient.post<Agent>('/agents', data, config);
    return response.data;
  }

  /**
   * Update an existing agent
   * Requires DEPOT_ADMIN or SUPER_ADMIN role
   * @param id - Agent ID
   * @param data - Agent data to update
   * @param depotId - Required for SUPER_ADMIN to specify depot context
   */
  async update(id: string, data: UpdateAgentRequest, depotId?: string): Promise<Agent> {
    const config = depotId ? {
      headers: { 'x-depot-id': depotId }
    } : {};
    const response = await apiClient.put<Agent>(`/agents/${id}`, data, config);
    return response.data;
  }

  /**
   * Reset agent PIN - generates new PIN and returns it (one-time view)
   * Requires DEPOT_ADMIN or SUPER_ADMIN role
   * @param id - Agent ID
   * @param depotId - Required for SUPER_ADMIN to specify depot context
   */
  async resetPin(id: string, depotId?: string): Promise<Agent> {
    const config = depotId ? {
      headers: { 'x-depot-id': depotId }
    } : {};
    const response = await apiClient.post<Agent>(`/agents/${id}/reset-pin`, {}, config);
    return response.data;
  }
}

export const agentService = new AgentService();
