import { z } from 'zod';

export const loginSchema = z.object({
  body: z.object({
    username: z.string(),
    password: z.string(),
  }),
});

export const forgotPasswordSchema = z.object({
  body: z.object({
    email: z.string().email('A valid email is required'),
  }),
});

export const resetPasswordSchema = z.object({
  body: z.object({
    token: z.string().min(1, 'Reset token is required'),
    new_password: z.string().min(8, 'Password must be at least 8 characters'),
  }),
});

export const depotSchema = z.object({
  body: z.object({
    merchant_code: z.string()
      .length(6, 'Merchant code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Merchant code must be 3 uppercase letters + 3 digits (e.g., HRE001)'),
    name: z.string(),
    location: z.string().optional(),
  }),
});

export const updateDepotSchema = z.object({
  params: z.object({
    id: z.string(),
  }),
  body: z.object({
    merchant_code: z.string()
      .length(6, 'Merchant code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Merchant code must be 3 uppercase letters + 3 digits (e.g., HRE001)'),
    name: z.string(),
    location: z.string().optional(),
  }),
});

export const agentSchema = z.object({
  body: z.object({
    full_name: z.string(),
    // These fields are auto-generated by backend if not provided
    username: z.string().optional(),
    agent_code: z.string()
      .length(6, 'Agent code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Agent code must be 3 uppercase letters + 3 digits (e.g., TMO014)')
      .optional(), // Made optional - will be auto-generated if not provided
    pin: z.string().min(4).max(6).optional(),
    status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED']).optional().default('ACTIVE'),
  }),
});

export const deviceSchema = z.object({
  body: z.object({
    serial_number: z.string(),
    token: z.string().optional(),
  }),
});

export const fleetSchema = z.object({
  body: z.object({
    number: z.string(),
    status: z.enum(['ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED']).optional(),
    capacity: z.number().int().min(0).optional(),
  }),
});

export const routeSchema = z.object({
  body: z.object({
    origin: z.string(),
    destination: z.string(),
    is_active: z.boolean().optional(),
    distance_km: z.number().positive().optional(),
  }),
});

export const fareSchema = z.object({
  body: z.object({
    route_id: z.string(),
    currency: z.string(),
    amount: z.coerce.number(),
  }),
});

export const startTripSchema = z.object({
  body: z.object({
    agent_id: z.string(),
    fleet_id: z.string(),
    route_id: z.string().optional(),
    device_id: z.string().optional(),
    started_offline: z.boolean().optional(),
  }),
});

export const endTripSchema = z.object({ params: z.object({ id: z.string() }) });

export const ticketIssueSchema = z.object({
  body: z.object({
    trip_id: z.string(),
    agent_id: z.string().optional(), // Optional – falls back to the authenticated agent from JWT
    device_id: z.string().optional(),
    ticket_category: z.enum(['PASSENGER', 'PASSENGER_WITH_LUGGAGE', 'LUGGAGE']),
    currency: z.string(),
    amount: z.coerce.number(),
    departure: z.string().optional(),
    destination: z.string().optional(),
    issued_at: z.string().optional(),
    linked_passenger_ticket_id: z.string().optional(),
    passenger_name: z.string().trim().min(2, 'Passenger name must be at least 2 characters').max(100).optional(),
    passenger_phone: z
      .string()
      .trim()
      .min(7, 'Passenger phone must be at least 7 digits')
      .max(20, 'Passenger phone is too long')
      .regex(/^[+]?[\d\s()-]+$/, 'Passenger phone contains invalid characters')
      .optional(),
  }).superRefine((data, ctx) => {
    const requiresPassengerDetails =
      data.ticket_category === 'PASSENGER' ||
      data.ticket_category === 'PASSENGER_WITH_LUGGAGE' ||
      data.ticket_category === 'LUGGAGE';

    if (requiresPassengerDetails) {
      if (!data.passenger_name) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['passenger_name'],
          message: 'Passenger name is required for this ticket type',
        });
      }
      if (!data.passenger_phone) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['passenger_phone'],
          message: 'Passenger phone is required for this ticket type',
        });
      }
    }
  }),
});

export const ticketVoidSchema = z.object({
  params: z.object({ id: z.string() }),
  body: z.object({
    reason: z.string(),
    agent_id: z.string().optional(),
    device_id: z.string().optional(),
  }),
});

export const ticketSearchSchema = z.object({
  query: z.object({
    serial_number: z.coerce.number().optional(),
    ticket_id: z.string().optional(),
    trip_id: z.string().optional(),
  }),
});

export const syncPushSchema = z.object({
  body: z.object({
    trips: z.array(z.any()).optional(),
    tickets: z.array(z.any()).optional(),
  }),
});

export const syncPullSchema = z.object({
  query: z.object({ since: z.string().optional() }),
});
