import { z } from 'zod';

export const loginSchema = z.object({
  body: z.object({
    username: z.string(),
    password: z.string(),
  }),
});

export const forgotPasswordSchema = z.object({
  body: z.object({
    email: z.string().email('A valid email is required'),
  }),
});

export const resetPasswordSchema = z.object({
  body: z.object({
    token: z.string().min(1, 'Reset token is required'),
    new_password: z.string().min(8, 'Password must be at least 8 characters'),
  }),
});

export const depotSchema = z.object({
  body: z.object({
    merchant_code: z.string()
      .length(6, 'Merchant code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Merchant code must be 3 uppercase letters + 3 digits (e.g., HRE001)'),
    name: z.string(),
    location: z.string().optional(),
  }),
});

export const updateDepotSchema = z.object({
  params: z.object({
    id: z.string(),
  }),
  body: z.object({
    merchant_code: z.string()
      .length(6, 'Merchant code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Merchant code must be 3 uppercase letters + 3 digits (e.g., HRE001)'),
    name: z.string(),
    location: z.string().optional(),
  }),
});

export const agentSchema = z.object({
  body: z.object({
    full_name: z.string(),
    // These fields are auto-generated by backend if not provided
    username: z.string().optional(),
    agent_code: z.string()
      .length(6, 'Agent code must be exactly 6 characters')
      .regex(/^[A-Z]{3}\d{3}$/, 'Agent code must be 3 uppercase letters + 3 digits (e.g., TMO014)')
      .optional(), // Made optional - will be auto-generated if not provided
    pin: z.string().min(4).max(6).optional(),
    status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED']).optional().default('ACTIVE'),
  }),
});

export const deviceSchema = z.object({
  body: z.object({
    serial_number: z.string().min(1, 'Serial number is required'),
    token: z.string().optional(),
  }),
});

export const updateDeviceSchema = z.object({
  params: z.object({
    id: z.string().min(1),
  }),
  body: z.object({
    serial_number: z.string().min(1, 'Serial number is required').optional(),
    depot_id: z.string().min(1).optional(),
  }).refine((data) => data.serial_number !== undefined || data.depot_id !== undefined, {
    message: 'Provide serial_number and/or depot_id to update',
  }),
});

const expiryDateField = z
  .string()
  .optional()
  .nullable()
  .refine((val) => !val || !Number.isNaN(new Date(val).getTime()), {
    message: 'Invalid expiry date',
  });

export const fleetSchema = z.object({
  body: z.object({
    number: z.string().min(1, 'Fleet number is required'),
    status: z.enum(['ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED']).optional(),
    capacity: z.coerce.number().int().min(0).optional(),
    licence_disc_expiry: expiryDateField,
    cof_expiry: expiryDateField,
    passenger_liability_expiry: expiryDateField,
    route_authority_expiry: expiryDateField,
    ppa_expiry: expiryDateField,
  }),
});

export const fleetUpdateSchema = z.object({
  body: z.object({
    number: z.string().min(1).optional(),
    status: z.enum(['ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED']).optional(),
    capacity: z.coerce.number().int().min(0).optional(),
    licence_disc_expiry: expiryDateField,
    cof_expiry: expiryDateField,
    passenger_liability_expiry: expiryDateField,
    route_authority_expiry: expiryDateField,
    ppa_expiry: expiryDateField,
  }),
});

export const routeSchema = z.object({
  body: z.object({
    origin: z.string(),
    destination: z.string(),
    parent_route_id: z.string().optional().nullable(),
    parent_route_ids: z.array(z.string()).optional(),
    child_route_ids: z.array(z.string()).optional(),
    is_active: z.boolean().optional(),
    distance_km: z.number().positive().optional(),
  }),
});

export const fareSchema = z.object({
  body: z.object({
    route_id: z.string(),
    currency: z.string(),
    amount: z.coerce.number(),
  }),
});

export const startTripSchema = z.object({
  body: z.object({
    agent_id: z.string(),
    fleet_id: z.string(),
    route_id: z.string().optional(),
    device_id: z.string().optional(),
    started_offline: z.boolean().optional(),
  }),
});

export const endTripSchema = z.object({ params: z.object({ id: z.string() }) });

export const ticketIssueSchema = z.object({
  body: z
    .object({
      trip_id: z.string(),
      agent_id: z.string().optional(), // Optional – falls back to the authenticated agent from JWT
      device_id: z.string().optional(),
      ticket_category: z.enum(['PASSENGER', 'PASSENGER_WITH_LUGGAGE', 'LUGGAGE']),
      currency: z.string(),
      /** Total ticket charge. For PASSENGER_WITH_LUGGAGE = passenger fare + luggage_amount. */
      amount: z.coerce.number().positive('Amount must be greater than 0'),
      /** Manual luggage charge (required for PASSENGER_WITH_LUGGAGE). */
      luggage_amount: z.coerce.number().positive().optional(),
      departure: z.string().optional(),
      destination: z.string().optional(),
      issued_at: z.string().optional(),
      linked_passenger_ticket_id: z.string().optional(),
      // Passenger name is no longer collected; accept legacy payloads and ignore.
      passenger_name: z.string().trim().max(100).optional(),
      passenger_phone: z.preprocess(
        (val) => (typeof val === 'string' && val.trim() === '' ? undefined : val),
        z
          .string()
          .trim()
          .min(7, 'Passenger phone must be at least 7 digits')
          .max(20, 'Passenger phone is too long')
          .regex(/^[+]?[\d\s()-]+$/, 'Passenger phone contains invalid characters')
          .optional(),
      ),
      luggage_description: z.preprocess(
        (val) => (typeof val === 'string' && val.trim() === '' ? undefined : val),
        z
          .string()
          .trim()
          .min(2, 'Luggage description is too short')
          .max(80, 'Luggage description must be 80 characters or less')
          .optional(),
      ),
    })
    .superRefine((data, ctx) => {
      if (data.ticket_category === 'PASSENGER_WITH_LUGGAGE') {
        if (data.luggage_amount == null) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            path: ['luggage_amount'],
            message: 'Luggage amount is required for passenger + luggage tickets',
          });
          return;
        }
        if (data.amount <= data.luggage_amount) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            path: ['amount'],
            message:
              'Total amount must include the passenger fare plus the luggage charge',
          });
        }
      }
    }),
});

export const ticketVoidSchema = z.object({
  params: z.object({ id: z.string() }),
  body: z.object({
    reason: z.string(),
    agent_id: z.string().optional(),
    device_id: z.string().optional(),
  }),
});

export const ticketSearchSchema = z.object({
  query: z.object({
    serial_number: z.coerce.number().optional(),
    ticket_id: z.string().optional(),
    trip_id: z.string().optional(),
  }),
});

export const syncPushSchema = z.object({
  body: z.object({
    trips: z.array(z.any()).optional(),
    tickets: z.array(z.any()).optional(),
  }),
});

export const syncPullSchema = z.object({
  query: z.object({ since: z.string().optional() }),
});
